FROM :python3.9
COPY ./dplot_server.py ./
COPY ./data ./data
COPY ./logs ./logs
COPY ./requirements.txt ./
RUN pip install -r requirements.txt



##  
##  cd projekt/ projekt itog
## docker build -t p2_анализ_image ./p2_анализ

###  
## COPY ./uwsgi_docker_config.ini ./uwsgi.ini
